### ISSUE TITLE
Compatibility with apollo3-cache-persist (Reopening issue 35)

### ISSUE THREAD

**Issue by ericaiq** [NerdWalletOSS/apollo-cache-policies#47] opened 2022-01-31 07:46 UTC
Hi, I'm having trouble using `apollo-cache-policies` along with the `apollo3-cache-persist` library in a React Native project. This issue is most likely the same as #35.  I have gotten an `InvalidationPolicyCache` to work without persistence. However the data is never refreshed once I persist the cache.

 I modified a sandbox to repro the issue [here](https://codesandbox.io/s/apollo-cache-policies-forked-nniyn?file=/src/App.js). (Original sandbox from [this issue](https://github.com/NerdWalletOSS/apollo-cache-policies/issues/39))

Repro Steps:
1. Click a film
2. Wait 10 seconds for cache to expire
3. Navigate back

Expected:
4. List is refreshed with a new network request

Actual:
4. List is not refreshed, the data is loaded from the cache.

The same steps result in the list being refreshed if apollo-cache-persist is not being used (comment out line 47). Any advice for getting these two libraries to work?

Let me know if you need more info. Also, this is my first time working with Apollo. This could easily be my fault. Thanks!

**Comment by mogelbrod** [comment] 2022-01-31 10:13
I also noticed this recently as I'm starting to experiment with cache invalidation more and more. To be fair I'm not entirely that using both libraries has ever worked for me - I might have accidentally temporarily disabled the persist plugin while testing.

Neither v1.5.0, v2.0.0, v2.0.2 nor v2.3.0 seems to ever invalidate entries when combined with [apollo-cache-persist@0.13.0](https://github.com/apollographql/apollo-cache-persist/blob/master/CHANGELOG.md).

**Comment by danReynolds** [comment] 2022-01-31 14:43
Thanks for the repro! I'll take a look later today

**Comment by danReynolds** [comment] 2022-02-03 22:16
Hey @ericaiq ! Getting back to this, had a busy week with work. Thanks for the great sandbox, found the issue. We had not been reinitializing all of the necessary objects when apollo3-cache-persist would call `cache.restore()` on startup, causing the TTLs to not work. Fixed in: https://github.com/NerdWalletOSS/apollo-cache-policies/pull/48 and released under version [2.4.0](https://www.npmjs.com/package/@nerdwallet/apollo-cache-policies). Let me know if that works for you!

**Comment by ericaiq** [comment] 2022-02-03 23:26
Thanks for looking into this! We actually decided to go in a different direction for the project I am working on. 

I'm still noticing some weirdness in the sandbox. Notably that the initial call to allFilms isn't cached. I'm not sure if this is a sandbox set up issue or an issue with the cache.

Repro:
1. Set apollo-cache-policies to 2.4.0
2. Click a film
3. wait 10 second (for cache to expire)
4. click back
5. The list of films is now empty (Expected behavior is that the list is refetched)
6. Click Load More
7. Click a film
7. Click back
8. List is still empty and new films are not fetched
9. Refresh page, list is still empty. I think there is an empty list in the cache?

**Comment by mogelbrod** [comment] 2022-02-16 09:57
Can confirm that what @ericaiq described above is happening for me too.

**Comment by danReynolds** [comment] 2022-02-16 19:47
@mogelbrod I think I found an issue and just released 2.4.1. When I run the original sandbox posted above on 2.4.1 (make sure to run `window.localStorage.clear()` to get rid of any lingering data from cache persist under 2.4.0) and perform steps 1-10 it seems to be working. If it's not too much trouble, take a look and see if it's still reproducible when you have time.

**Comment by mogelbrod** [comment] 2022-02-17 13:26
@danReynolds looks like v2.4.1 fixes the issue with relay style pagination, much appreciated!

**Comment by danReynolds** [comment] 2022-02-17 13:34
> @danReynolds looks like v2.4.1 fixes the issue with relay style pagination, much appreciated!

Woohoo! That was a tricky one. Thanks for your patience and persistence! 🙏

**Closed** 2022-02-17 15:56 UTC
